[project]
name = "youtube-to-podcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "John Engdal", email = "john@engdal.fi" }]
requires-python = ">=3.14"
dependencies = [
  "datastar-py>=1.0.2",
  "django>=6.1",
  "django-environ>=0.14.0",
  "msgspec>=0.21.1",
  "uvicorn>=0.52.3",
  "valkey-glide>=2.5.1",
]

[project.scripts]
ytp = "ytp:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

# [build-system]
# requires = ["setuptools"]
# build-backend = "setuptools.build_meta"

[tool.basedpyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]
executionEnvironments = [{ root = "src" }]

[tool.bandit]
exclude_dirs = [".venv"]

[tool.ruff]
namespace-packages = ["src/"]

[tool.uv.build-backend]
source-include = ["*.templates"]

# [tool.setuptools]
# package-dir = { "" = "src" }
#
# [tool.setuptools.packages.find]
# where = ["src"]
#
# [tool.setuptools.package-data]
# "example_app.templates" = ["**/*"]

[dependency-groups]
dev = [
  "basedpyright>=1.39.10",
  "django-browser-reload>=1.21.0",
  "django-debug-toolbar>=7.1.1",
  "ipython>=9.16.1",
  "ruff>=0.16.3",
]
