name: Bandit
on: [push, pull_request]

jobs:
  bandit:
    runs-on: nix
    steps:
      # new releases/commits: https://github.com/actions/checkout/releases
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/actions/setup-devenv
      - run: devenv --no-tui shell run_bandit
