"""Django settings for poddla project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    USE_HTTPS=(bool, False),
    VALKEY_PORT=(int, None),
    VALKEY_HOST=(str, "127.0.0.1"),
    VALKEY_DB=(int, 0),
    YOUTUBE_META_CACHE_SECONDS=(int, 3600),
    MEDIA_ROOT=(str, None),
    STATIC_ROOT=(str, str(BASE_DIR / "staticfiles")),
    BGUTIL_SERVER_HOME=(str, ""),
    LOG_LEVEL=(str, "DEBUG"),
    INITIAL_ADMIN_PASSWORD=(str, ""),
)
environ.Env.read_env(BASE_DIR.parent / ".env")

SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")
USE_HTTPS = env("USE_HTTPS")

if USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

SECURE_REFERRER_POLICY = "same-origin"


VALKEY_PORT = env("VALKEY_PORT")
VALKEY_HOST = env("VALKEY_HOST")
VALKEY_DB = env("VALKEY_DB")
YOUTUBE_META_CACHE_SECONDS = env("YOUTUBE_META_CACHE_SECONDS")
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(str(env("MEDIA_ROOT")))
BGUTIL_SERVER_HOME = env("BGUTIL_SERVER_HOME")
LOG_LEVEL = env("LOG_LEVEL")
# Used to create the initial 'admin' user:
# user_settings/management/commands/create_initial_admin.py.
INITIAL_ADMIN_PASSWORD = env("INITIAL_ADMIN_PASSWORD")

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django_http_compression",
    "podcasts",
    "valkey_changes",
    "user_settings",
    "poddla_settings",
]

if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")
    INSTALLED_APPS.append("django_browser_reload")
    INSTALLED_APPS.append("django_extensions")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_http_compression.middleware.HttpCompressionMiddleware",
]

if DEBUG:
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = "poddla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "poddla.wsgi.application"
TEST_RUNNER = "poddla.runner.Runner"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Auth
# https://docs.djangoproject.com/en/6.1/topics/auth/default/

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "podcasts"
LOGOUT_REDIRECT_URL = "login"

AUTHENTICATION_BACKENDS = ["poddla.backends.UserSettingsModelBackend"]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}
if DEBUG:
    STORAGES["staticfiles"]["BACKEND"] = "django.contrib.staticfiles.storage.StaticFilesStorage"


STATICFILES_DIRS = [
    BASE_DIR / "poddla" / "static",
]

# Where collectstatic will put files for production:
STATIC_ROOT = Path(env("STATIC_ROOT"))

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

# Logging
# https://docs.djangoproject.com/en/6.1/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}
