services:
  poddla:
    image: poddla:latest
    environment:
      VALKEY_HOST: valkey
      VALKEY_PORT: "6379"
      # CHANGE before deploying for real:
      # Use eg: `python -c "import secrets; print(secrets.token_urlsafe(50))":
      SECRET_KEY: "changeme-generate-a-real-secret-key"
      GRANIAN_HOST: "0.0.0.0"
      GRANIAN_PORT: "8000"
      GRANIAN_HTTP: "2"
      # CHANGE this and SITE_ADDRESS below:
      ALLOWED_HOSTS: localhost
      # CHANGE this too (include https:// or http://):
      CSRF_TRUSTED_ORIGINS: https://localhost:4444
      # Set to True if we're behind a https proxy:
      USE_HTTPS: "True"
      DEBUG: "False"
      DATABASE_URL: sqlite:////data/db/poddla.sqlite3
      MEDIA_ROOT: /data/media
      # CHANGE before deploying: sets the password for an automatically created 'admin' user.
      # Only used the first time - has no effect once an 'admin' user exists.
      INITIAL_ADMIN_PASSWORD: "changeme-generate-a-real-password"
    volumes:
      # Metadata about the podcasts will be stored in a sqlite file located here:
      - ./data/db:/data/db
      # The cached media will be stored here:
      - ./data/media:/data/media
    depends_on:
      - valkey
    restart: unless-stopped

  valkey:
    image: valkey/valkey:9.1.1
    volumes:
      - ./data/valkey:/data
    restart: unless-stopped

  caddy:
    image: caddy:2.11.4
    ports:
      - "4444:4444"
    environment:
      # If you want the RSS feeds to be used by podcast apps you'll have to
      # host poddla in such a way that their servers can access the feeds.
      # See the Caddyfile:
      SITE_ADDRESS: https://localhost:4444
      PODDLA_ADDRESS: h2c://poddla:8000
      # TRUSTED_PROXIES: 192.168.1.1/32
      MEDIA_ROOT: /data/media
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Caddy serves the media files:
      - ./data/media:/data/media
    depends_on:
      - poddla
    restart: unless-stopped
