# Generated by Django 6.1 on 2026-08-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=16)),
                ('source_type', models.CharField(blank=True, choices=[('channel', 'Channel'), ('playlist', 'Playlist')], max_length=16)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'public')), fields=('url',), name='unique_public_source_url')],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('show_notes', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcastfeed')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('failed', 'Failed')], default='pending', max_length=18)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='podcasts.episode')),
            ],
            options={
                'ordering': ['index', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('episode',), name='unique_download_per_episode')],
            },
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('podcast', 'youtube_id'), name='unique_episode_per_podcast'),
        ),
    ]
