# Generated by Django 6.1 on 2026-09-03 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoddlaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_feed_update_freq', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('media_files_expire', models.DurationField(default=datetime.timedelta(days=14))),
                ('media_files_expiry_enabled', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='poddla_settings_singleton')],
            },
        ),
    ]
