name: Setup devenv
description: Configure Nix caches and install devenv
runs:
  using: composite
  steps:
    - name: Configure Nix
      shell: bash
      run: |
        # NOTE: In my case this runs in a docker based runner that uses the hosts nix store.
        #       The host will also need to trust these caches for them to be used.
        cat >> /etc/nix/nix.conf <<'EOF'
        experimental-features = nix-command flakes
        extra-substituters = https://nix-community.cachix.org https://devenv.cachix.org https://nixpkgs-python.cachix.org
        extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= nixpkgs-python.cachix.org-1:hxjI7pFxTyuTHn2NkvWCrAUcNZLNS3ZAvfYNuYifcEU=
        narinfo-cache-negative-ttl = 0
        EOF
    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
    - name: Init devenv
      shell: bash
      run: devenv shell --no-tui /bin/true
